/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type ArticleList = {
  _type: "articleList";
  heading?: string;
  intro?: string;
  source?: "latest" | "selected";
  topic?: CategoryReference;
  limit?: number;
  articles?: Array<
    {
      _key: string;
    } & PostReference
  >;
  action?: Action;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type SimpleRichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "heading" | "subheading" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & MediaImage)
>;

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  name?: string;
  context?: string;
  portrait?: MediaImage;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: SimpleRichText;
};

export type FeatureItem = {
  _type: "featureItem";
  heading?: string;
  body?: string;
  image?: MediaImage;
  link?: Action;
};

export type Action = {
  _type: "action";
  label?: string;
  destination?: Link;
};

export type CallToAction = {
  _type: "callToAction";
  heading?: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Action
  >;
};

export type Testimonials = {
  _type: "testimonials";
  heading?: string;
  intro?: string;
  items?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type Faqs = {
  _type: "faqs";
  heading?: string;
  intro?: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type Features = {
  _type: "features";
  heading?: string;
  intro?: string;
  items?: Array<
    {
      _key: string;
    } & FeatureItem
  >;
};

export type TextSection = {
  _type: "textSection";
  heading?: string;
  content?: RichText;
};

export type Hero = {
  _type: "hero";
  heading?: string;
  lede?: string;
  image?: MediaImage;
  actions?: Array<
    {
      _key: string;
    } & Action
  >;
  alignment?: "start" | "center";
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & TextSection)
  | ({
      _key: string;
    } & Features)
  | ({
      _key: string;
    } & Faqs)
  | ({
      _key: string;
    } & Testimonials)
  | ({
      _key: string;
    } & CallToAction)
  | ({
      _key: string;
    } & ArticleList)
>;

export type SocialLink = {
  _type: "socialLink";
  platform?:
    | "linkedin"
    | "instagram"
    | "facebook"
    | "youtube"
    | "x"
    | "tiktok"
    | "bluesky"
    | "github";
  url?: string;
};

export type NavigationLink = {
  _type: "navigationLink";
  label?: string;
  destination?: Link;
};

export type NavigationGroup = {
  _type: "navigationGroup";
  label?: string;
  links?: Array<
    {
      _key: string;
    } & NavigationLink
  >;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  linkType?: "internal" | "external";
  internalTarget?: HomePageReference | PageReference | PostReference;
  externalUrl?: string;
  opensInNewTab?: boolean;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  author?: PersonReference;
  topics?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  excerpt?: string;
  mainImage?: MediaImage;
  body?: RichText;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  searchVisibility?: "visible" | "hidden";
  canonicalUrl?: string;
};

export type MediaImage = {
  _type: "mediaImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  role?: "informative" | "decorative";
  alt?: string;
  caption?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: MediaImage;
  bio?: SimpleRichText;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  outcome?: "permanent" | "temporary" | "gone";
  destination?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: MediaImage;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  description?: string;
  socialImage?: MediaImage;
  contactEmail?: string;
  contactPhone?: string;
  postalAddress?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: Array<
    | ({
        _key: string;
      } & NavigationLink)
    | ({
        _key: string;
      } & NavigationGroup)
  >;
  footer?: Array<
    | ({
        _key: string;
      } & NavigationLink)
    | ({
        _key: string;
      } & NavigationGroup)
  >;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageBuilder?: PageBuilder;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CategoryReference
  | PostReference
  | ArticleList
  | Category
  | SimpleRichText
  | RichText
  | Testimonial
  | FaqItem
  | FeatureItem
  | Action
  | CallToAction
  | Testimonials
  | Faqs
  | Features
  | TextSection
  | Hero
  | PageBuilder
  | SocialLink
  | NavigationLink
  | NavigationGroup
  | HomePageReference
  | PageReference
  | Link
  | PersonReference
  | Post
  | SanityImageAssetReference
  | Seo
  | MediaImage
  | Person
  | Slug
  | Redirect
  | SiteSettings
  | Navigation
  | HomePage
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/redirects.ts
// Variable: REDIRECTS_QUERY
// Query: *[_type == "redirect" && defined(source)]{  source,  destination,  outcome,  "permanent": outcome == "permanent"}
export type REDIRECTS_QUERY_RESULT = Array<{
  source: string;
  destination: string | null;
  outcome: "gone" | "permanent" | "temporary" | null;
  permanent: false | true;
}>;

// Source: ../src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  siteName,  description,  socialImage,  logo,  socialLinks,  contactEmail,  contactPhone,  postalAddress}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      siteName: null;
      description: null;
      socialImage: null;
      logo: null;
      socialLinks: null;
      contactEmail: null;
      contactPhone: null;
      postalAddress: null;
    }
  | {
      siteName: null;
      description: null;
      socialImage: null;
      logo: null;
      socialLinks: Array<
        {
          _key: string;
        } & SocialLink
      > | null;
      contactEmail: null;
      contactPhone: null;
      postalAddress: null;
    }
  | {
      siteName: null;
      description: string | null;
      socialImage: null;
      logo: null;
      socialLinks: null;
      contactEmail: null;
      contactPhone: null;
      postalAddress: null;
    }
  | {
      siteName: string | null;
      description: string | null;
      socialImage: MediaImage | null;
      logo: MediaImage | null;
      socialLinks: Array<
        {
          _key: string;
        } & SocialLink
      > | null;
      contactEmail: string | null;
      contactPhone: string | null;
      postalAddress: string | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{  _id,  _type,  title,  pageBuilder[]{    _type,    _key,    heading,    _type == "hero" => {      lede,      alignment,      image {    ...,    asset->{ _id, "metadata": metadata{ lqip } }  },      actions[]{        _key,        label,        destination {    ...,    internalTarget->{ _type, "slug": slug.current }  }      }    },    _type == "textSection" => {      content []{      ...,      markDefs[]{        ...,        _type == "link" => {    ...,    internalTarget->{ _type, "slug": slug.current }  }      },      _type == "mediaImage" => {    ...,    asset->{ _id, "metadata": metadata{ lqip } }  }    }    }  },  "seo": {    "title": coalesce(seo.title, title),    "description": coalesce(seo.description, excerpt),    "image": coalesce(seo.image, mainImage),    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),    "noIndex": seo.searchVisibility == "hidden",    "canonicalUrl": seo.canonicalUrl  }}
export type HOME_PAGE_QUERY_RESULT =
  | {
      _id: "homePage";
      _type: "category";
      title: string | null;
      pageBuilder: null;
      seo: {
        title: string | null;
        description: null;
        image: null;
        imageAlt: string | null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "homePage";
      title: string | null;
      pageBuilder: Array<
        | {
            _type: "articleList";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "callToAction";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "faqs";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "features";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "hero";
            _key: string;
            heading: string | null;
            lede: string | null;
            alignment: "center" | "start" | null;
            image: {
              _type: "mediaImage";
              asset: {
                _id: string;
                metadata: {
                  lqip: string | null;
                } | null;
              } | null;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              role?: "decorative" | "informative";
              alt?: string;
              caption?: string;
            } | null;
            actions: Array<{
              _key: string;
              label: string | null;
              destination: {
                _type: "link";
                linkType?: "external" | "internal";
                internalTarget:
                  | {
                      _type: "homePage";
                      slug: null;
                    }
                  | {
                      _type: "page";
                      slug: string | null;
                    }
                  | {
                      _type: "post";
                      slug: string | null;
                    }
                  | null;
                externalUrl?: string;
                opensInNewTab?: boolean;
              } | null;
            }> | null;
          }
        | {
            _type: "testimonials";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "textSection";
            _key: string;
            heading: string | null;
            content: Array<
              | {
                  children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                  }>;
                  style?: "blockquote" | "heading" | "normal" | "subheading";
                  listItem?: "bullet" | "number";
                  markDefs: Array<{
                    _key: string;
                    _type: "link";
                    linkType?: "external" | "internal";
                    internalTarget:
                      | {
                          _type: "homePage";
                          slug: null;
                        }
                      | {
                          _type: "page";
                          slug: string | null;
                        }
                      | {
                          _type: "post";
                          slug: string | null;
                        }
                      | null;
                    externalUrl?: string;
                    opensInNewTab?: boolean;
                  }> | null;
                  level?: number;
                  _type: "block";
                  _key: string;
                }
              | {
                  _key: string;
                  _type: "mediaImage";
                  asset: {
                    _id: string;
                    metadata: {
                      lqip: string | null;
                    } | null;
                  } | null;
                  media?: unknown;
                  hotspot?: SanityImageHotspot;
                  crop?: SanityImageCrop;
                  role?: "decorative" | "informative";
                  alt?: string;
                  caption?: string;
                  markDefs: null;
                }
            > | null;
          }
      > | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
        imageAlt: string | null;
        noIndex: false | true;
        canonicalUrl: string | null;
      };
    }
  | {
      _id: "homePage";
      _type: "navigation";
      title: null;
      pageBuilder: null;
      seo: {
        title: null;
        description: null;
        image: null;
        imageAlt: null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "page";
      title: string | null;
      pageBuilder: Array<
        | {
            _type: "articleList";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "callToAction";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "faqs";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "features";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "hero";
            _key: string;
            heading: string | null;
            lede: string | null;
            alignment: "center" | "start" | null;
            image: {
              _type: "mediaImage";
              asset: {
                _id: string;
                metadata: {
                  lqip: string | null;
                } | null;
              } | null;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              role?: "decorative" | "informative";
              alt?: string;
              caption?: string;
            } | null;
            actions: Array<{
              _key: string;
              label: string | null;
              destination: {
                _type: "link";
                linkType?: "external" | "internal";
                internalTarget:
                  | {
                      _type: "homePage";
                      slug: null;
                    }
                  | {
                      _type: "page";
                      slug: string | null;
                    }
                  | {
                      _type: "post";
                      slug: string | null;
                    }
                  | null;
                externalUrl?: string;
                opensInNewTab?: boolean;
              } | null;
            }> | null;
          }
        | {
            _type: "testimonials";
            _key: string;
            heading: string | null;
          }
        | {
            _type: "textSection";
            _key: string;
            heading: string | null;
            content: Array<
              | {
                  children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                  }>;
                  style?: "blockquote" | "heading" | "normal" | "subheading";
                  listItem?: "bullet" | "number";
                  markDefs: Array<{
                    _key: string;
                    _type: "link";
                    linkType?: "external" | "internal";
                    internalTarget:
                      | {
                          _type: "homePage";
                          slug: null;
                        }
                      | {
                          _type: "page";
                          slug: string | null;
                        }
                      | {
                          _type: "post";
                          slug: string | null;
                        }
                      | null;
                    externalUrl?: string;
                    opensInNewTab?: boolean;
                  }> | null;
                  level?: number;
                  _type: "block";
                  _key: string;
                }
              | {
                  _key: string;
                  _type: "mediaImage";
                  asset: {
                    _id: string;
                    metadata: {
                      lqip: string | null;
                    } | null;
                  } | null;
                  media?: unknown;
                  hotspot?: SanityImageHotspot;
                  crop?: SanityImageCrop;
                  role?: "decorative" | "informative";
                  alt?: string;
                  caption?: string;
                  markDefs: null;
                }
            > | null;
          }
      > | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
        imageAlt: string | null;
        noIndex: false | true;
        canonicalUrl: string | null;
      };
    }
  | {
      _id: "homePage";
      _type: "person";
      title: null;
      pageBuilder: null;
      seo: {
        title: null;
        description: null;
        image: null;
        imageAlt: null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "post";
      title: string | null;
      pageBuilder: null;
      seo: {
        title: string | null;
        description: string | null;
        image:
          | MediaImage
          | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: "image";
            }
          | null;
        imageAlt: string | null;
        noIndex: false | true;
        canonicalUrl: string | null;
      };
    }
  | {
      _id: "homePage";
      _type: "redirect";
      title: null;
      pageBuilder: null;
      seo: {
        title: null;
        description: null;
        image: null;
        imageAlt: null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "sanity.fileAsset";
      title: string | null;
      pageBuilder: null;
      seo: {
        title: string | null;
        description: null;
        image: null;
        imageAlt: string | null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "sanity.imageAsset";
      title: string | null;
      pageBuilder: null;
      seo: {
        title: string | null;
        description: null;
        image: null;
        imageAlt: string | null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | {
      _id: "homePage";
      _type: "siteSettings";
      title: null;
      pageBuilder: null;
      seo: {
        title: null;
        description: null;
        image: null;
        imageAlt: null;
        noIndex: false;
        canonicalUrl: null;
      };
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  _type,  title,  "slug": slug.current,  pageBuilder[]{    _type,    _key,    heading,    _type == "hero" => {      lede,      alignment,      image {    ...,    asset->{ _id, "metadata": metadata{ lqip } }  },      actions[]{        _key,        label,        destination {    ...,    internalTarget->{ _type, "slug": slug.current }  }      }    },    _type == "textSection" => {      content []{      ...,      markDefs[]{        ...,        _type == "link" => {    ...,    internalTarget->{ _type, "slug": slug.current }  }      },      _type == "mediaImage" => {    ...,    asset->{ _id, "metadata": metadata{ lqip } }  }    }    }  },  "seo": {    "title": coalesce(seo.title, title),    "description": coalesce(seo.description, excerpt),    "image": coalesce(seo.image, mainImage),    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),    "noIndex": seo.searchVisibility == "hidden",    "canonicalUrl": seo.canonicalUrl  }}
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  title: string | null;
  slug: string | null;
  pageBuilder: Array<
    | {
        _type: "articleList";
        _key: string;
        heading: string | null;
      }
    | {
        _type: "callToAction";
        _key: string;
        heading: string | null;
      }
    | {
        _type: "faqs";
        _key: string;
        heading: string | null;
      }
    | {
        _type: "features";
        _key: string;
        heading: string | null;
      }
    | {
        _type: "hero";
        _key: string;
        heading: string | null;
        lede: string | null;
        alignment: "center" | "start" | null;
        image: {
          _type: "mediaImage";
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          role?: "decorative" | "informative";
          alt?: string;
          caption?: string;
        } | null;
        actions: Array<{
          _key: string;
          label: string | null;
          destination: {
            _type: "link";
            linkType?: "external" | "internal";
            internalTarget:
              | {
                  _type: "homePage";
                  slug: null;
                }
              | {
                  _type: "page";
                  slug: string | null;
                }
              | {
                  _type: "post";
                  slug: string | null;
                }
              | null;
            externalUrl?: string;
            opensInNewTab?: boolean;
          } | null;
        }> | null;
      }
    | {
        _type: "testimonials";
        _key: string;
        heading: string | null;
      }
    | {
        _type: "textSection";
        _key: string;
        heading: string | null;
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "blockquote" | "heading" | "normal" | "subheading";
              listItem?: "bullet" | "number";
              markDefs: Array<{
                _key: string;
                _type: "link";
                linkType?: "external" | "internal";
                internalTarget:
                  | {
                      _type: "homePage";
                      slug: null;
                    }
                  | {
                      _type: "page";
                      slug: string | null;
                    }
                  | {
                      _type: "post";
                      slug: string | null;
                    }
                  | null;
                externalUrl?: string;
                opensInNewTab?: boolean;
              }> | null;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              _key: string;
              _type: "mediaImage";
              asset: {
                _id: string;
                metadata: {
                  lqip: string | null;
                } | null;
              } | null;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              role?: "decorative" | "informative";
              alt?: string;
              caption?: string;
              markDefs: null;
            }
        > | null;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    imageAlt: string | null;
    noIndex: false | true;
    canonicalUrl: string | null;
  };
} | null;

// Source: ../src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  _type,  title,  "slug": slug.current,  publishedAt,  _updatedAt,  excerpt,  mainImage,  author->{name, role},  topics[]->{title},  "seo": {    "title": coalesce(seo.title, title),    "description": coalesce(seo.description, excerpt),    "image": coalesce(seo.image, mainImage),    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),    "noIndex": seo.searchVisibility == "hidden",    "canonicalUrl": seo.canonicalUrl  }}
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  excerpt: string | null;
  mainImage: MediaImage | null;
  author: {
    name: string | null;
    role: string | null;
  } | null;
  topics: Array<{
    title: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image:
      | MediaImage
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        }
      | null;
    imageAlt: string | null;
    noIndex: false | true;
    canonicalUrl: string | null;
  };
} | null;

// Source: ../src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)] | order(_id) [0...1000].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(_id) [0...1000].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: {  "home": *[_id == "homePage" && seo.searchVisibility != "hidden"][0]{ _updatedAt },  "pages": *[_type == "page" && defined(slug.current) && seo.searchVisibility != "hidden"]    | order(_id) [0...5000]{ "slug": slug.current, _updatedAt },  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"      && publishedAt <= now()]    | order(_id) [0...5000]{ "slug": slug.current, _updatedAt }}
export type SITEMAP_QUERY_RESULT = {
  home: {
    _updatedAt: string;
  } | null;
  pages: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: LLMS_QUERY
// Query: {  "site": *[_id == "siteSettings"][0]{ siteName, description },  "home": *[_id == "homePage" && seo.searchVisibility != "hidden"][0]{    title,    "description": seo.description  },  "pages": *[_type == "page" && defined(slug.current) && seo.searchVisibility != "hidden"]    | order(title asc) [0...1000]{      title,      "slug": slug.current,      "description": seo.description    },  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"      && publishedAt <= now()]    | order(publishedAt desc) [0...1000]{      title,      "slug": slug.current,      publishedAt,      "description": coalesce(seo.description, excerpt)    }}
export type LLMS_QUERY_RESULT = {
  site:
    | {
        siteName: null;
        description: null;
      }
    | {
        siteName: null;
        description: string | null;
      }
    | {
        siteName: string | null;
        description: string | null;
      }
    | null;
  home:
    | {
        title: null;
        description: null;
      }
    | {
        title: string | null;
        description: null;
      }
    | {
        title: string | null;
        description: string | null;
      }
    | null;
  pages: Array<{
    title: string | null;
    slug: string | null;
    description: string | null;
  }>;
  posts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    description: string | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: LLMS_FULL_QUERY
// Query: {  "site": *[_id == "siteSettings"][0]{ siteName, description },  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"      && publishedAt <= now()]    | order(publishedAt desc) [0...200]{      title,      "slug": slug.current,      publishedAt,      "description": coalesce(seo.description, excerpt),      author->{ name },      body    }}
export type LLMS_FULL_QUERY_RESULT = {
  site:
    | {
        siteName: null;
        description: null;
      }
    | {
        siteName: null;
        description: string | null;
      }
    | {
        siteName: string | null;
        description: string | null;
      }
    | null;
  posts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    description: string | null;
    author: {
      name: string | null;
    } | null;
    body: RichText | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "redirect" && defined(source)]{\n  source,\n  destination,\n  outcome,\n  "permanent": outcome == "permanent"\n}': REDIRECTS_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n  siteName,\n  description,\n  socialImage,\n  logo,\n  socialLinks,\n  contactEmail,\n  contactPhone,\n  postalAddress\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_id == "homePage"][0]{\n  _id,\n  _type,\n  title,\n  pageBuilder[]{\n    _type,\n    _key,\n    heading,\n\n    _type == "hero" => {\n      lede,\n      alignment,\n      image {\n    ...,\n    asset->{ _id, "metadata": metadata{ lqip } }\n  },\n      actions[]{\n        _key,\n        label,\n        destination {\n    ...,\n    internalTarget->{ _type, "slug": slug.current }\n  }\n      }\n    },\n\n    _type == "textSection" => {\n      content []{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => {\n    ...,\n    internalTarget->{ _type, "slug": slug.current }\n  }\n      },\n      _type == "mediaImage" => {\n    ...,\n    asset->{ _id, "metadata": metadata{ lqip } }\n  }\n    }\n    }\n  },\n  "seo": {\n    "title": coalesce(seo.title, title),\n    "description": coalesce(seo.description, excerpt),\n    "image": coalesce(seo.image, mainImage),\n    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),\n    "noIndex": seo.searchVisibility == "hidden",\n    "canonicalUrl": seo.canonicalUrl\n  }\n}': HOME_PAGE_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  pageBuilder[]{\n    _type,\n    _key,\n    heading,\n\n    _type == "hero" => {\n      lede,\n      alignment,\n      image {\n    ...,\n    asset->{ _id, "metadata": metadata{ lqip } }\n  },\n      actions[]{\n        _key,\n        label,\n        destination {\n    ...,\n    internalTarget->{ _type, "slug": slug.current }\n  }\n      }\n    },\n\n    _type == "textSection" => {\n      content []{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => {\n    ...,\n    internalTarget->{ _type, "slug": slug.current }\n  }\n      },\n      _type == "mediaImage" => {\n    ...,\n    asset->{ _id, "metadata": metadata{ lqip } }\n  }\n    }\n    }\n  },\n  "seo": {\n    "title": coalesce(seo.title, title),\n    "description": coalesce(seo.description, excerpt),\n    "image": coalesce(seo.image, mainImage),\n    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),\n    "noIndex": seo.searchVisibility == "hidden",\n    "canonicalUrl": seo.canonicalUrl\n  }\n}': PAGE_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  _updatedAt,\n  excerpt,\n  mainImage,\n  author->{name, role},\n  topics[]->{title},\n  "seo": {\n    "title": coalesce(seo.title, title),\n    "description": coalesce(seo.description, excerpt),\n    "image": coalesce(seo.image, mainImage),\n    "imageAlt": coalesce(seo.image.alt, mainImage.alt, title),\n    "noIndex": seo.searchVisibility == "hidden",\n    "canonicalUrl": seo.canonicalUrl\n  }\n}': POST_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)] | order(_id) [0...1000].slug.current': PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(_id) [0...1000].slug.current': POST_SLUGS_QUERY_RESULT;
    '{\n  "home": *[_id == "homePage" && seo.searchVisibility != "hidden"][0]{ _updatedAt },\n  "pages": *[_type == "page" && defined(slug.current) && seo.searchVisibility != "hidden"]\n    | order(_id) [0...5000]{ "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"\n      && publishedAt <= now()]\n    | order(_id) [0...5000]{ "slug": slug.current, _updatedAt }\n}': SITEMAP_QUERY_RESULT;
    '{\n  "site": *[_id == "siteSettings"][0]{ siteName, description },\n  "home": *[_id == "homePage" && seo.searchVisibility != "hidden"][0]{\n    title,\n    "description": seo.description\n  },\n  "pages": *[_type == "page" && defined(slug.current) && seo.searchVisibility != "hidden"]\n    | order(title asc) [0...1000]{\n      title,\n      "slug": slug.current,\n      "description": seo.description\n    },\n  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"\n      && publishedAt <= now()]\n    | order(publishedAt desc) [0...1000]{\n      title,\n      "slug": slug.current,\n      publishedAt,\n      "description": coalesce(seo.description, excerpt)\n    }\n}': LLMS_QUERY_RESULT;
    '{\n  "site": *[_id == "siteSettings"][0]{ siteName, description },\n  "posts": *[_type == "post" && defined(slug.current) && seo.searchVisibility != "hidden"\n      && publishedAt <= now()]\n    | order(publishedAt desc) [0...200]{\n      title,\n      "slug": slug.current,\n      publishedAt,\n      "description": coalesce(seo.description, excerpt),\n      author->{ name },\n      body\n    }\n}': LLMS_FULL_QUERY_RESULT;
  }
}
