#!/usr/bin/env node

/**
 * Design token build: tokens/*.json → src/app/tokens.css
 *
 * Plain ESM rather than a TypeScript config, so the pipeline needs no TS runner.
 * Style Dictionary 5 is ESM-native and this file is short; adding tsx to type a
 * 100-line build script is the kind of sprawl the stack doc warns about.
 *
 * WHY THERE IS A MANUAL EXPORT STEP
 * Figma's Variables REST API is Enterprise-only, and this project is on Pro, so
 * tokens cannot be pulled automatically. They are exported from Figma with a
 * plugin and committed as the JSON in this directory — see tokens/README.md.
 * That is not purely a downside: because the export is committed, a brand change
 * arrives as a reviewable diff, which is what WP3 actually asked for.
 *
 * OUTPUT CONTRACT
 * Emits :root and .dark blocks only. The @theme inline mapping and @layer base
 * rules stay hand-written in globals.css — they are structure, not brand, and
 * regenerating them would mean this script owned Tailwind's configuration too.
 */

import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import StyleDictionary from 'style-dictionary'
import { checkMode } from './contrast.mjs'

const TOKENS = new URL('.', import.meta.url).pathname
const OUT = 'src/app/'

/* ── Parity check ──────────────────────────────────────────────────────────
 * A semantic token present in one mode and missing from the other produces a
 * variable that is simply absent under that selector. The component then
 * inherits whatever the cascade offers, so the bug appears in one theme only
 * and reviews right past anyone testing in the other. Cheap to check, so it is
 * checked rather than trusted. */
function assertModeParity() {
  const read = (f) => JSON.parse(readFileSync(join(TOKENS, 'semantic', f), 'utf8'))
  const names = (o) => new Set(Object.keys(o).filter((k) => !k.startsWith('$')))

  const light = names(read('light.json'))
  const dark = names(read('dark.json'))

  const onlyLight = [...light].filter((n) => !dark.has(n))
  const onlyDark = [...dark].filter((n) => !light.has(n))

  if (onlyLight.length || onlyDark.length) {
    const lines = [
      'Semantic tokens must exist in BOTH light.json and dark.json.',
      onlyLight.length ? `  missing from dark.json:  ${onlyLight.join(', ')}` : '',
      onlyDark.length ? `  missing from light.json: ${onlyDark.join(', ')}` : '',
      '',
      'A token defined in only one mode is undefined under the other selector,',
      'so the component silently inherits a value and the bug shows in one theme only.',
    ].filter(Boolean)
    throw new Error(lines.join('\n'))
  }
  return light.size
}

const header = (mode) =>
  `/* GENERATED by tokens/build.mjs — do not edit.\n` +
  ` * Source: tokens/${mode}. Regenerate with \`pnpm tokens\`.\n` +
  ` * Edit the JSON, not this file: the next build overwrites it. */\n`

/** Reference tier + light semantics under :root. */
const lightConfig = {
  source: [join(TOKENS, 'reference/**/*.json'), join(TOKENS, 'semantic/light.json')],
  include: [join(TOKENS, 'component/**/*.json')],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: OUT,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            /* Emit `var(--brand-900)` rather than the resolved colour, so the
               reference → semantic chain stays visible in the built CSS. The
               indirection is the point: it is what makes a rebrand a change to
               tier 1 alone. */
            outputReferences: true,
          },
        },
      ],
    },
  },
}

/** Dark semantics only, under .dark. References resolve against :root. */
const darkConfig = {
  source: [join(TOKENS, 'reference/**/*.json'), join(TOKENS, 'semantic/dark.json')],
  /* Suppresses one specific, expected warning: the filter below removes the
     reference tier from THIS file's output, and Style Dictionary cannot know
     those variables are still defined in :root from the light build. They are.
     Silenced deliberately so the build stays quiet — a build that always prints
     a warning is a build whose warnings nobody reads. */
  log: { warnings: 'disabled' },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: OUT,
      files: [
        {
          destination: 'tokens.dark.css',
          format: 'css/variables',
          filter: (token) => token.filePath.includes('semantic/dark.json'),
          options: { selector: '.dark', outputReferences: true },
        },
      ],
    },
  },
}

/* ── Contrast gate ─────────────────────────────────────────────────────────
 * WCAG 2.2 AA is the project's first non-negotiable, and it is a property of a
 * PAIR of tokens, not of either one. A rebrand changes tier 1 only and leaves
 * the semantic tier pointing at the same rungs, so the UI restyles itself and
 * looks correct while contrast quietly moves. Swapping the neutral ramp for a
 * blue one of similar lightness took muted-foreground from 4.74:1 to 3.69:1 —
 * a real AA failure for body text that nothing on screen announces. */
function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue
    const name = prefix ? `${prefix}-${k}` : k
    if (v && typeof v === 'object') {
      if ('$value' in v) out[name] = v.$value
      else flatten(v, name, out)
    }
  }
  return out
}

function assertContrast() {
  const load = (p) => JSON.parse(readFileSync(join(TOKENS, p), 'utf8'))
  const reference = readdirSync(join(TOKENS, 'reference'))
    .filter((f) => f.endsWith('.json'))
    .reduce((acc, f) => Object.assign(acc, flatten(load(join('reference', f)))), {})

  const results = ['light', 'dark'].map((mode) =>
    checkMode(mode, { ...reference, ...flatten(load(join('semantic', `${mode}.json`))) }),
  )

  const failures = results.flatMap((r) => r.failures)
  const skipped = results.flatMap((r) => r.skipped)

  for (const s of skipped) console.log(`  · skipped ${s.pair} — ${s.why}`)

  if (failures.length) {
    const lines = [
      'WCAG 2.2 AA contrast failures in the token set:',
      '',
      ...failures.map(
        (f) =>
          `  ${f.mode.padEnd(5)} ${f.pair.padEnd(46)} ${f.ratio}:1  (needs ${f.min}:1 — ${f.note})`,
      ),
      '',
      'Fix by adjusting the REFERENCE ramp these resolve to, not by pointing the',
      'semantic token somewhere arbitrary — the ramp is what a rebrand changes, and',
      'a one-off override will break again on the next one.',
    ]
    throw new Error(lines.join('\n'))
  }
  return results.flatMap((r) => r.passes).length
}

const count = assertModeParity()
const checked = assertContrast()

const light = new StyleDictionary(lightConfig)
await light.buildAllPlatforms()

const dark = new StyleDictionary(darkConfig)
await dark.buildAllPlatforms()

/* Style Dictionary writes one selector per run, so the two outputs are stitched
   into a single file. One import in globals.css is easier to reason about than
   two, and keeps the ordering explicit rather than dependent on import order. */
const { writeFileSync, rmSync } = await import('node:fs')
const lightCss = readFileSync(join(OUT, 'tokens.css'), 'utf8')
const darkCss = readFileSync(join(OUT, 'tokens.dark.css'), 'utf8')

const strip = (s) => s.replace(/^\/\*\*[\s\S]*?\*\/\n*/, '').trim()

writeFileSync(
  join(OUT, 'tokens.css'),
  `${header('')}\n${strip(lightCss)}\n\n${strip(darkCss)}\n`,
)
rmSync(join(OUT, 'tokens.dark.css'))

const files = readdirSync(join(TOKENS, 'reference')).length
console.log(
  `\n✔ tokens.css written — ${count} semantic tokens × 2 modes, ${files} reference files` +
    `\n✔ ${checked} contrast pairs pass WCAG 2.2 AA`,
)
